# Generated by Django 3.2.8 on 2021-10-15 01:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Max 100 characters.', max_length=100, null=True)),
                ('model', models.CharField(help_text='Max 100 characters.', max_length=100, null=True)),
            ],
            options={
                'unique_together': {('make', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='api.car')),
            ],
        ),
    ]
